#!/bin/bash

#
# (C) 2012 Nextworks SRL
#
# Written by: Francesco  Salvestrini <f DOT salvestrini AT nextworks DOT it>
#             Alessandro Canessa     <a DOT canessa AT nextworks DOT it>
#

DEFAULT_BUILDDIR=`pwd`/.build
DEFAULT_DESTDIR=`pwd`/.env

ME="install"

BUILDDIR=$1
if test -z "${BUILDDIR}" ; then
    BUILDDIR=$DEFAULT_BUILDDIR
    echo "${ME}: Missing build directory, using default $BUILDDIR"
fi
shift
mkdir -p $BUILDDIR || {
    echo "${ME}: Cannot create $BUILDDIR directory"
    exit 1
}

DESTDIR=$1
if test -z "${DESTDIR}" ; then
    DESTDIR=$DEFAULT_DESTDIR
    echo "${ME}: Missing destination directory, using default $DESTDIR"
fi
shift
mkdir -p $DESTDIR || {
    echo "${ME}: Cannot create $DESTDIR directory"
    exit 1
}

(cd src/topologymgr && ./bootstrap && PATH=$DESTDIR/bin:$PATH CPPFLAGS=-I`pwd`../.dest/include ./configure --prefix=$DESTDIR && make install) || {
    echo "${ME}: Cannot configure/install package"
    exit 1
}

rm -r -f $BUILDDIR
