#
# Makefile.am
#
# (C) 2009 Nextworks SRL
#
# Written by: Francesco Salvestrini <f DOT salvestrini AT nextworks DOT it>
#

.PHONY: AUTHORS
AUTHORS:
	$(GIT) log --format="%aN <%aE>" | $(SORT) | $(UNIQ) > AUTHORS || {	\
		rm -f AUTHORS ;							\
		exit 1 ;							\
        }

EXTRA_DIST     += AUTHORS
DISTCLEANFILES += AUTHORS

BUILT_SOURCES  += $(top_srcdir)/.version
$(top_srcdir)/.version:
	echo $(VERSION) > $@-t && mv $@-t $@

dist-hook:
	echo $(VERSION) > $(distdir)/.tarball-version
