# DO NOT EDIT THIS FILE!
#
# Python module Topology__POA generated by omniidl

import omniORB
omniORB.updateModule("Topology__POA")

# ** 1. Stub files contributing to this module
import topology_idl

# ** 2. Sub-modules

# ** 3. End
